# Generated by Django 3.2.3 on 2021-05-30 12:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
