# Generated by Django 3.2.4 on 2021-08-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('img', models.ImageField(upload_to='Advertisement/', verbose_name='الصوره')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('img', models.ImageField(upload_to='Photos/', verbose_name='الصوره')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='السؤال')),
                ('first_choice', models.CharField(max_length=250, verbose_name='الأختيار الأول')),
                ('yes', models.IntegerField(default=0, verbose_name='نعم')),
                ('second_choice', models.CharField(max_length=250, verbose_name='الأختيار الثاني')),
                ('no', models.IntegerField(default=0, verbose_name='لا')),
                ('all', models.IntegerField(default=0, verbose_name='عدد الأصوات')),
                ('approval', models.BooleanField(default=True, verbose_name='الأتاحه')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('type', models.CharField(choices=[('contributor', 'مساهم'), ('writer', 'كاتب'), ('editor', 'محرر'), ('editor_in_chief', 'رئيس تحرير'), ('chairman', 'رئيس مجلس اداره')], max_length=15)),
                ('name', models.CharField(max_length=125, verbose_name='name')),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('email', models.EmailField(max_length=125, unique=True, verbose_name='email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='is_superuser')),
                ('role', models.CharField(choices=[('ADMIN', 'ADMIN'), ('STAFF', 'STAFF')], max_length=125, verbose_name='role')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is_staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
            },
        ),
    ]
