# Generated by Django 3.2.3 on 2021-05-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('contributor', 'مساهم'), ('writer', 'كاتب'), ('editor', 'محرر'), ('editor_in_chief', 'رئيس تحرير'), ('chairman', 'رئيس مجلس اداره')], max_length=15),
        ),
    ]
