# Generated by Django 3.2.4 on 2021-07-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='السؤال')),
                ('yes', models.IntegerField(default=0, verbose_name='لا')),
                ('no', models.IntegerField(default=0, verbose_name='نعم')),
                ('all', models.IntegerField(default=0, verbose_name='عدد الأصوات')),
            ],
        ),
        migrations.AlterField(
            model_name='advertising',
            name='img',
            field=models.ImageField(upload_to='Advertisement/', verbose_name='الصوره'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='title',
            field=models.CharField(max_length=200, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(upload_to='Photos/', verbose_name='الصوره'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=200, verbose_name='العنوان'),
        ),
    ]
