# Generated by Django 3.2.4 on 2021-07-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210702_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='approval',
            field=models.BooleanField(default=False, verbose_name='الأتاحه'),
        ),
    ]
