# Generated by Django 3.2.4 on 2021-07-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_survey_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='first_choice',
            field=models.CharField(default='نعم', max_length=250, verbose_name='الأختيار الأول'),
        ),
        migrations.AddField(
            model_name='survey',
            name='second_choice',
            field=models.CharField(default='لا', max_length=250, verbose_name='الأختيار الثاني'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='no',
            field=models.IntegerField(default=0, verbose_name='لا'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='yes',
            field=models.IntegerField(default=0, verbose_name='نعم'),
        ),
    ]
