# Generated by Django 3.2.4 on 2021-07-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210705_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='first_choice',
            field=models.CharField(max_length=250, verbose_name='الأختيار الأول'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='second_choice',
            field=models.CharField(max_length=250, verbose_name='الأختيار الثاني'),
        ),
    ]
