# Generated by Django 3.2.3 on 2021-05-22 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
