# Generated by Django 3.2.3 on 2021-05-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='auther',
            field=models.CharField(default='nohammed', max_length=100),
            preserve_default=False,
        ),
    ]
