# Generated by Django 3.2.3 on 2021-05-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_tag_tag_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-Publish_date']},
        ),
    ]
