# Generated by Django 3.2.3 on 2021-06-01 16:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_news_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='approval',
            field=models.BooleanField(default=False, verbose_name='الموافقه'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='news',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='البيانات'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='الصوره'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='news',
            name='viewCount',
            field=models.IntegerField(default=0, verbose_name='عدد المشاهديين'),
        ),
    ]
