# Generated by Django 3.2.3 on 2021-06-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20210601_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='user',
        ),
        migrations.DeleteModel(
            name='Advertising',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
