# Generated by Django 3.2.3 on 2021-06-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20210605_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='commentCount',
            field=models.IntegerField(default=0, verbose_name='عدد التعليقات'),
        ),
    ]
