# Generated by Django 3.2.4 on 2021-07-01 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_remove_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NEWS', to='news.category', verbose_name='القسم'),
        ),
    ]
