# Generated by Django 3.2.4 on 2021-07-03 16:01

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0018_auto_20210703_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NEWS', to='news.category', verbose_name='القسم'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('Publish_date', models.DateTimeField(auto_now_add=True)),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='البيانات')),
                ('img', models.ImageField(upload_to='books/', verbose_name='الصوره')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-Publish_date'],
            },
        ),
    ]
