# Generated by Django 3.2.4 on 2021-07-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_auto_20210703_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='viewCount',
            field=models.IntegerField(default=0, verbose_name='عدد المشاهديين'),
        ),
    ]
