# Generated by Django 3.2.4 on 2021-07-04 17:53

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0020_book_viewcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('Publish_date', models.DateTimeField(auto_now_add=True)),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='البيانات')),
                ('img', models.ImageField(upload_to='books/', verbose_name='الصوره')),
                ('viewCount', models.IntegerField(default=0, verbose_name='عدد المشاهديين')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-Publish_date'],
            },
        ),
    ]
